#!/usr/bin/env bash
set -euo pipefail

# 域名分组配置文件（仓库根目录下的 JSON 文件）
DOMAINS_FILE="${1:-Domains.json}"
OUTPUT_FILE="${2:-hosts}"

if [[ ! -f "$DOMAINS_FILE" ]]; then
  echo "错误: 找不到域名配置文件 $DOMAINS_FILE" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "错误: 需要安装 jq 以解析 JSON 文件" >&2
  exit 1
fi

# 写入 hosts 文件头部注释
cat > "$OUTPUT_FILE" << EOF
# Auto-generated hosts file
# Generated by GitHub Actions on $(date)
# IPv6 addresses are listed first, IPv4 as additional entries
EOF

current_group=""

# 按 Domains.json 的顺序遍历每个分组：
# JSON 格式为 { "GroupName": ["domain1", "domain2", ...], ... }
# 直接以组名作为注释标题，不再添加额外前缀
jq -r 'to_entries[] | "# \(.key)", (.value[] | .)' "$DOMAINS_FILE" |
while IFS= read -r line; do
  # 判断是否为分组标题行（以 "# " 开头且不是头部注释）
  if [[ "$line" == "# "* ]] && [[ "$line" != "# Auto-generated"* ]] && [[ "$line" != "# Generated"* ]] && [[ "$line" != "# IPv6"* ]]; then
    # 通过字符串截取获取组名，完全避免使用 BASH_REMATCH
    group_name="${line#\# }"
    echo "# $group_name" >> "$OUTPUT_FILE"
    current_group="$group_name"
  elif [[ -n "$line" && "$line" != \#* ]]; then
    echo "Resolving $line... (group: ${current_group:-unknown})" >&2
    # 解析 IPv6 地址（|| true 防止 grep 无匹配时 set -e 中断）
    ipv6=$(dig AAAA +short +time=3 +tries=2 "$line" | grep -E '^[0-9a-fA-F:]+$' | head -n 1 || true)
    # 解析 IPv4 地址
    ipv4=$(dig A +short +time=3 +tries=2 "$line" | grep -E '^[0-9.]+$' | head -n 1 || true)
    # 如果解析到 IPv6，则优先写入 IPv6
    if [[ -n "${ipv6:-}" ]]; then
      echo "$ipv6 $line" >> "$OUTPUT_FILE"
      echo "Added IPv6: $ipv6 for $line" >&2
    fi
    # 如果解析到 IPv4，则继续写入 IPv4
    if [[ -n "${ipv4:-}" ]]; then
      echo "$ipv4 $line" >> "$OUTPUT_FILE"
      echo "Added IPv4: $ipv4 for $line" >&2
    fi
    # 两者均未解析到，输出警告信息
    if [[ -z "${ipv6:-}" && -z "${ipv4:-}" ]]; then
      echo "警告: Failed to resolve $line (both IPv6 and IPv4)" >&2
    fi
    # 每个域名之后加一个空行，提升可读性
    echo "" >> "$OUTPUT_FILE"
  fi
done

# 打印生成的 hosts 文件内容便于排查
echo "Generated hosts file:" >&2
cat "$OUTPUT_FILE"