# This is a basic workflow to help you get started with Actions

name: Get IP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-hosts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Set up environment
        run: |
          sudo apt-get update && sudo apt-get install -y dnsutils

      # Runs a set of commands using the runners shell
      - name: Define domain groups
        id: define_domains
        env:
          DOMAIN_GROUPS: |
            # GROUP: Group1_DLsite
            login.dlsite.com
            ssl.dlsite.com
            www.dlsite.com
            www.nijiyome.com
            www.nijiyome.jp
            download.dlsite.com
            ci-en.dlsite.com
            play.dlsite.com
            # GROUP: Group2_Itch.io
            i.ytimg.com
            img.itch.zone
            itch.io
            static.itch.io
            # GROUP: Group3_Deviantart
            deviantart.com
            www.deviantart.com
            email.mg.deviantart.com
            st.deviantart.net
            a.deviantart.net
            e.deviantart.net
            i.deviantart.net
            t00.deviantart.net
            static.parastorage.com
            api-da.wixmp.com
            deviantart.net
            parastorage.com
            # GROUP: Group4_Discord
            cdn.discordapp.com
            discordapp.com
            discord.com
            discord.gg
            discord.app
            updates.discord.com
            media.discordapp.net
            latency.discord.media
            remote-auth-gateway.discord.gg
            # GROUP: Group5_recaptcha
            ajax.googleapis.com
            gapis.geekzu.org
            www.recaptcha.google.com
            recaptcha.net
            gstatic.com
            gstatic.cn
            google.com
        run: |
          echo "groups<<EOF" >> $GITHUB_OUTPUT
          echo "$DOMAIN_GROUPS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate annotated hosts file
        run: |
          cat > hosts << EOF
          # Auto-generated hosts file
          # Generated by GitHub Actions on $(date)
          EOF

          groups="${{ steps.define_domains.outputs.groups }}"
          current_group=""

          while IFS= read -r line; do
            if [[ "$line" =~ ^#\ GROUP:\ (.+) ]]; then
              group_name="${BASH_REMATCH[1]}"
              echo "# $group_name" >> hosts
              current_group="$group_name"
            elif [[ -n "$line" && "$line" != \#* ]]; then
              ip=$(dig +short +time=3 +tries=2 "$line" | grep -E '^[0-9.]+$' | head -n 1)
              if [[ -n "$ip" ]]; then
                echo "$ip $line" >> hosts
              else
                echo "⚠️ Failed to resolve $line" >&2
              fi
            fi
          done <<< "$groups"

          cat hosts

      - name: Commit hosts file to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if git diff --quiet --exit-code hosts; then
            echo "No changes to hosts file"
            exit 0
          fi

          git add hosts
          git commit -m "Update hosts file - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
